spring:
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=spring_boot_3
    user: postgres
    password: password
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5433/postgres?currentSchema=spring_boot_3
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    
server:
  port: 8080
  servlet:
    context-path: /spring_boot_3